# public/admin/config.yml
backend:
  name: github
  repo: sharathalt1-byte/Sharathnakka
  branch: main

media_folder: "public/uploads"  # where uploaded media will go (in your repo)
public_folder: "/uploads"       # URL path to access media

media_library:
  name: uploadcare   # or cloudinary, or local (uploadcare is easiest for testing)
  config:
    publicKey: "demopublickey" # Uploadcare demo key, works for testing

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
