backend:
  name: github
  repo: sharathalt1-byte/Sharathnakka
  branch: main

media_folder: "public/uploads"   # relative to repo root
public_folder: "/uploads"        # relative to site root

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
